Update Makefile
Fixes the following error during build due to rt library not linking:  undefined reference to symbol 'timer_settime@@GLIBC_2.3.3'
# http://stackoverflow.com/questions/18286738/undefined-reference-to-symbol-timer-settimeglibc-2-3-3/18809357#18809357