Update Makefile.target
Fixes the following error during build due to rt library not linking:  undefined reference to symbol 'timer_settime@@GLIBC_2.3.3'